Update expected ListOptions
        --- FAIL: TestCompatibility/core.v1.ListOptions/v1.14.0 (0.02s)
            compatibility.go:472: proto differs
            compatibility.go:474:   strings.Join({
                  	... // 10 identical lines
                  	"  7: 6780787122834727873",
                  	`  8: "5"`,
                + 	"  9: 0",
                  	"}",
                  	`3: ""`,
                  	... // 2 identical lines
                  }, "\n")

Caused by https://github.com/kubernetes/kubernetes/pull/74074/files#diff-eca3b8d856fa2e661f6da91b61de5e76R364