e2e storage: add compile test for public TestSuite API
This will catch accidentally adding a new interface function which
isn't exported. For example, an attempt to implement a new unexported
"foobar()" function then leads to:

test/e2e/storage/testsuites/api_test.go:54:5: cannot use &fakeSuite literal (type *fakeSuite) as type testsuites.TestSuite in assignment:
	*fakeSuite does not implement testsuites.TestSuite (missing testsuites.foobar method)
		have foobar()
		want testsuites.foobar()
FAIL	k8s.io/kubernetes/test/e2e/storage/testsuites [build failed]